spring.application.name=mypetstore
petstore.api.url=https://petstore.swagger.io/v2
server.port=8080

# Allure
allure.results.directory=target/allure-results

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/mypetshop
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.file.enabled=true
logging.file.path=logs

logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.springframework.http.client=DEBUG
logging.level.org.springframework.web=DEBUG
